version: 1

formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s] %(message)s'
  method:
    format: '%(asctime)s %(name)s:%(funcName)s [%(levelname)s] %(message)s'
  trace:
    format: '%(asctime)s %(name)s@%(filename)s:%(lineno)d:%(funcName)s [%(levelname)s] %(message)s'
  input:
    format: '%(message)s'
  output:
    format: '#%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

loggers:
  root:
    class: Logger
    level: INFO
    handlers:
    - console
